var mHtmlhead = ''
var mHtmlbody = ''
var mHtmlfoot = ''

mHtmlhead += '<!DOCTYPE html>'
mHtmlhead += '<html xmlns="http://www.w3.org/1999/xhtml"><head>'
mHtmlhead += '<meta http-equiv="Content-Type" content="text/html; charset=utf-8">'
mHtmlhead += '<meta name="viewport" content="width=device-width">'
mHtmlhead += '<title>Torondoyweb</title><style type="text/css">'
mHtmlhead += '#outlook a{padding:0;}'
mHtmlhead += '.ReadMsgBody{width:100%;} .ExternalClass{width:100%;}'
mHtmlhead += '.ExternalClass, .ExternalClass p, .ExternalClass span, .ExternalClass font, .ExternalClass td, '
mHtmlhead += '.ExternalClass div {line-height: 100%;}'
mHtmlhead += 'body, table, td, a{-webkit-text-size-adjust:100%; -ms-text-size-adjust:100%;}'
mHtmlhead += 'table, td{mso-table-lspace:0pt; mso-table-rspace:0pt;}'
mHtmlhead += 'img{-ms-interpolation-mode:bicubic;}'
mHtmlhead += 'body{margin:0; padding:0;}'
mHtmlhead += 'img{border:0; height:auto; line-height:100%; outline:none; text-decoration:none;}'
mHtmlhead += 'table{border-collapse:collapse !important;}'
mHtmlhead += 'body{height:100% !important; margin:0; padding:0; width:100% !important;}'
mHtmlhead += '@media only screen and (max-width: 640px) {'
mHtmlhead += 'a[href^="tel"], a[href^="sms"] {'
mHtmlhead += 'text-decoration: none;'
mHtmlhead += 'color: #0066cc;'
mHtmlhead += 'pointer-events: none;'
mHtmlhead += 'cursor: default;}'
mHtmlhead += '.mobile_link a[href^="tel"], .mobile_link a[href^="sms"] {'
mHtmlhead += 'text-decoration: default;'
mHtmlhead += 'color: #0066cc !important;'
mHtmlhead += 'pointer-events: auto;'
mHtmlhead += 'cursor: default;}'
mHtmlhead += 'table[class="devicewidth"] {width: 440px!important;}'
mHtmlhead += 'table[class="devicewidthmob"] {width: 420px!important;}'
mHtmlhead += 'table[class="devicewidthinner"] {width: 420px!important;}'
mHtmlhead += 'img[class="banner"] {width: 440px!important;height:157px!important;}'
mHtmlhead += 'img[class="col2img"] {width: 440px!important;height:400px!important;}'
mHtmlhead += 'img[class="blog"] {width: 420px!important;height: 245px!important;}}'
mHtmlhead += '@media only screen and (max-width: 480px) {'
mHtmlhead += 'a[href^="tel"], a[href^="sms"] {'
mHtmlhead += 'text-decoration: none;'
mHtmlhead += 'color: #0066cc;'
mHtmlhead += 'pointer-events: none;'
mHtmlhead += 'cursor: default;}'
mHtmlhead += '.mobile_link a[href^="tel"], .mobile_link a[href^="sms"] {'
mHtmlhead += 'text-decoration: default;'
mHtmlhead += 'color: #0066cc !important;' 
mHtmlhead += 'pointer-events: auto;'
mHtmlhead += 'cursor: default;}'
mHtmlhead += 'table[class="devicewidth"] {width: 280px!important;}'
mHtmlhead += 'table[class="devicewidthmob"] {width: 260px!important;}'
mHtmlhead += 'table[class="devicewidthinner"] {width: 260px!important;}'
mHtmlhead += 'img[class="banner"] {width: 280px!important;height:100px!important;}'
mHtmlhead += 'img[class="col2img"] {width: 280px!important;height:260px!important;}'
mHtmlhead += 'img[class="blog"] {width: 260px!important;height: 152px!important;}'
mHtmlhead += 'td[class="padding-top-right15"]{padding:15px 15px 0 0 !important;}'
mHtmlhead += 'td[class="padding-right15"]{padding-right:15px !important;}}'
mHtmlhead += '</style></head>'
mHtmlhead += '<body bgcolor="white" style="-webkit-text-size-adjust: 100%;-ms-text-size-adjust: 100%;'
mHtmlhead += 'margin: 0;padding: 0;width: 100% !important;">'
mHtmlhead += '<table class="devicewidth" style="border-collapse: collapse; mso-table-lspace: 0pt; '
mHtmlhead += 'mso-table-rspace: 0pt;" border="0" width="560" cellspacing="0" '
mHtmlhead += 'cellpadding="0" align="center">'
mHtmlhead += '<tbody><tr>'

mHtmlbody += '<td align="center">'
mHtmlbody += '<p align="justify" style="color: #005dab; text-decoration: none; font-size: 25px; '
mHtmlbody += 'line-height: 1.2; font-weight: normal; font-family: "Lato","Helvetica Neue",'
mHtmlbody += 'Helvetica,Arial,sans-serif; text-align: left;">'
mHtmlbody += 'Gracias por Registrarte en nuestro portal '
mHtmlbody += 'estarás recibiendo noticias relevante a repuestos '
mHtmlbody += 'Automotriz'
mHtmlbody += '</p>'
mHtmlbody += '</td>'

mHtmlfoot += '</tr></tbody></table>'
mHtmlfoot += '<table class="devicewidth" style="border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt;" border="0" width="560" cellspacing="0" cellpadding="0" align="center">'
mHtmlfoot += '<tbody><tr>'
mHtmlfoot += '</tr><tr>'
mHtmlfoot += '<td align="center"><a style="text-decoration: none; color: #005eb8;"'
mHtmlfoot += 'href="#" target="_blank" rel="noopener"> '
mHtmlfoot += '<img style="display: block; border: none; outline: none; -ms-interpolation-mode: bicubic;'
mHtmlfoot += 'text-decoration: none; margin: auto;" '
mHtmlfoot += 'src="https://s26.postimg.org/uqso182rt/logo.jpg" alt="Torondoyweb" '
mHtmlfoot += 'width="224" height="138" border="0" hspace="0" vspace="0" /> '
mHtmlfoot += '</a></td></tbody></table>'
mHtmlfoot += '<table class="devicewidth" style="-webkit-border-radius: 4px; -moz-border-radius: 4px; border-radius: 4px; border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt;" border="0" width="560" cellspacing="0" cellpadding="0" align="center">'
mHtmlfoot += '<tbody><tr><td width="100%" height="20">&#160;</td>'
mHtmlfoot += '</tr><tr><td>'
mHtmlfoot += '<table class="devicewidthmob" border="0" width="180" cellspacing="0" cellpadding="0" align="center"'
mHtmlfoot += '><tbody><tr><td class="padding-right15" align="right" valign="middle" width="45"><a style="text-decoration: none; color: #005eb8;" href="#" target="_blank" rel="noopener"> <img style="display: block; border: none; outline: none; -ms-interpolation-mode: bicubic; text-decoration: none; margin: auto;" src="https://s26.postimg.org/7p3cn4sd5/btnyoutube.png" alt="Taringa!" width="38" height="34" border="0" hspace="0" vspace="0" /> </a></td>'
mHtmlfoot += '<td class="padding-right15" align="center" valign="middle" width="45"><a style="text-decoration: none; color: #005eb8;" href="#" target="_blank" rel="noopener"> <img style="display: block; border: none; outline: none; -ms-interpolation-mode: bicubic; text-decoration: none; margin: auto;" src="https://s26.postimg.org/ymx9oui55/btnface.png" alt="Taringa! en Facebook" width="38" height="34" border="0" hspace="0" vspace="0" /> </a></td>'
mHtmlfoot += '<td class="padding-right15" align="right" valign="middle" width="45"><a style="text-decoration: none; color: #005eb8;" href="#" target="_blank" rel="noopener"> <img style="display: block; border: none; outline: none; -ms-interpolation-mode: bicubic; text-decoration: none; margin: auto;" src="https://s26.postimg.org/3sq0r4znt/btntwiter.png" alt="Taringa! en Twitter" width="38" height="34" border="0" hspace="0" vspace="0" /> </a></td>'
mHtmlfoot += '<td class="padding-right15" align="right" valign="middle" width="45"><a style="text-decoration: none; color: #005eb8;" href="#" target="_blank" rel="noopener"> <img style="display: block; border: none; outline: none; -ms-interpolation-mode: bicubic; text-decoration: none; margin: auto;" src="https://s26.postimg.org/tbid45bi1/btninstagram.png" alt="Taringa! en Instagram" width="38" height="34" border="0" hspace="0" vspace="0" /> </a></td>'
mHtmlfoot += '</tr></tbody></table></td></tr><tr><td width="100%" height="20">&#160;</td></tr><tr>'
mHtmlfoot += '<td width="100%" height="10">&#160;</td></tr></tbody></table></body></html>'

//correo:{user: 'torondoyweb@gmail.com',pass:'875698741', servicio:'gmail'},

module.exports = {
	db:{host:'localhost',port:'3306',user:'root',password:'123',database:'jorge'},
	instancia:{host:'localhost',port:'3306',user:'root',password:'123'},
	encriptacion:{secreto:'heydicastro'},
	correo:	{ service: 'gmail',auth: {user: 'torondoyweb@gmail.com',pass:'875698741'} },
	correofrom: {from :'torondoyweb@gmail.com'},
	html:{cabecera:mHtmlhead, cuerpo:mHtmlbody, pie:mHtmlfoot}
}
